src/IBM.WatsonDeveloperCloud.SpeechToText/v1/ISpeechToTextService.cs
src/IBM.WatsonDeveloperCloud.SpeechToText/v1/Model/SpeechRecognitionAlternative.cs
src/IBM.WatsonDeveloperCloud.SpeechToText/v1/Model/SpeechRecognitionResult.cs
src/IBM.WatsonDeveloperCloud.SpeechToText/v1/Model/WordAlternativeResult.cs
src/IBM.WatsonDeveloperCloud.SpeechToText/v1/SpeechToTextService.cs
test/IBM.WatsonDeveloperCloud.SpeechToText.UnitTests/SpeechToTextServiceUnitTest.cs

1. Interface default params should match default params of implementation so the interface can be used as described in examples.
2.  Replaced `FileStream` with `Stream` and removed usage of filename passed to form. (API does not seem to require this). By using `FileStream`, we're assuming the source of the stream is a file, changing this to `Stream` allows the consumer of the library to determine what type of stream it is.
This does not break anything.

SpeechToTextService made more developer friendly

---

appveyor.yml

From now on I want to use `release` branch to prep for release. I want to tag and push `master` branch to nuget. Also I generate documentation on `master` branch rather than release.

use Master to tag and release from now on

---

src/IBM.WatsonDeveloperCloud/Constants.cs

User agent is now following the format `watson-apis-[language]-sdk/[version]`

Revised user-agent to standard format

---

src/IBM.WatsonDeveloperCloud/Http/Filters/ErrorFilter.cs

A validation has been added in the [ErrorFilter](https://github.com/watson-developer-cloud/dotnet-standard-sdk/blob/development/src/IBM.WatsonDeveloperCloud/Http/Filters/ErrorFilter.cs) class, whether it will check whether the return is a json. If positive, we will deserialize to type [Error](https://github.com/watson-developer-cloud/dotnet-standard-sdk/blob/development/src/IBM.WatsonDeveloperCloud/Http/Exceptions/Error.cs), if not, we will get the message returned and instantiate a new object of type [Error](https://github.com/watson-developer-cloud/dotnet-standard-sdk/blob/development/src/IBM.WatsonDeveloperCloud/Http/Exceptions/Error.cs).

Fixed: validation if response is json

---

src/IBM.WatsonDeveloperCloud.Conversation.v1/README.md

Updated the link that went to the WDC for Conversation service docs. They have moved to Bluemix Docs.

Updated conversation doc link

---

src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/Model/ClassifiedImage.cs
src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/Model/Face.cs
src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/Model/ImageWithFaces.cs
src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/VisualRecognitionService.cs
src/IBM.WatsonDeveloperCloud/Util/TokenManager.cs
test/IBM.WatsonDeveloperCloud.VisualRecognition.v3.IntegrationTests/VisualRecognitionServiceCFIntegrationTests.cs
test/IBM.WatsonDeveloperCloud.VisualRecognition.v3.IntegrationTests/VisualRecognitionServiceRCIntegrationTests.cs

This pull request regenerates Visual Recognition with IAM support. We now default to the `gateway` endpoint and change the endpoint to `gateway-a` if the user instantiates with CF `apikey` rather than `TokenOptions`.
Additionally, two sets of tests were added (CF and RC). The RC tests are not being run since we don't have credentials in the credential github repo and I don't have permission to create an RC instance.

Regenerate Visual Recognition with IAM Support

---

src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/VisualRecognitionService.cs
src/IBM.WatsonDeveloperCloud/Util/Credentials.cs
src/IBM.WatsonDeveloperCloud/Util/TokenManager.cs
test/IBM.WatsonDeveloperCloud.VisualRecognition.v3.IntegrationTests/VisualRecognitionServiceRCIntegrationTests.cs

This pull request disambiguates the IamUrl and service url by adding a ServiceUrl to the options model Previously we were using the IamUrl field to set the service url and the true IamUrl was hard coded into the TokenManager. Now the IamUrl is user configurable and defaults to `https://iam.bluemix.net/identity/token`.

4609 iam url

---

src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/IVisualRecognitionServiceExtension.cs
src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/VisualRecognitionServiceExtension.cs
src/IBM.WatsonDeveloperCloud/Service/IWatsonService.cs
src/IBM.WatsonDeveloperCloud/Service/WatsonService.cs

Fixes #248 
This pull request moves the SetCredential(apikey) method from the base service to the VisualRecognition extension. Users of other services were trying to authenticate using this method and IAM apikey. This will remove the confusion as they will not be able to SetCredential(apikey) from any service other than Visual Recognition.

Move SetCredential(apikey)

---

src/IBM.WatsonDeveloperCloud/Service/WatsonService.cs
test/IBM.WatsonDeveloperCloud.LanguageTranslator.v3.IntegrationTests/LTServiceIntTestBasicAuthIamApikey.cs

This pull request adds functionality to automatically get an authorization token when authenticating with basicauth using username `apikey` and password <iamapikey>.

Use authorization token when authenticating with IAM Apikey

---

IBM.WatsonDeveloperCloud.sln
test/IBM.WatsonDeveloperCloud.Discovery.v1.UnitTests/DiscoveryUnitTests.cs

This pull request adds Discovery Credentials unit tests. Also, some unit tests were fixed to read from results instead of response. Finally, LTv3 tests and examples are now correctly named.

Discovery credentials unit tests

---

src/IBM.WatsonDeveloperCloud/Http/Filters/ErrorFilter.cs

This pull request simplifies a check in the error filter. We use null conditional instead of directly checking if `ContentType` is not set in headers.

refactor(error-filter): simplify check for headers and content type

---

examples/IBM.WatsonDeveloperCloud.SpeechToText.v1.Example/SpeechToTextServiceExample.cs
src/IBM.WatsonDeveloperCloud.SpeechToText.v1/SpeechToTextService.cs
test/IBM.WatsonDeveloperCloud.SpeechToText.v1.IntegrationTests/SpeechToTextServiceIntegrationTest.cs

Training acoustic resources for speech to text requires an audio clip of at least 10 minutes. We were running tests and examples with a shorter audio clip and used an undocumented query parameter `force` when calling the service to train the acoustic model. This query param was handwritten in the service and required a post generation revision.
This pull request changes the acoustic resource to a file that is longer than 10 minutes and removes the handwritten `force` query parameter.

Update acoustic resource

---

src/IBM.WatsonDeveloperCloud.SpeechToText.v1/SpeechToTextServiceExtension.cs

This pull request adds deprecation messages to all sessions methods. Additionally a deprecation message was added to recognize methods using metadata since the Speech to Text service no longer supports this.

Deprecate sessions

---

src/IBM.WatsonDeveloperCloud.TextToSpeech.v1/TextToSpeechService.cs
src/IBM.WatsonDeveloperCloud/Http/Request.cs

If you try to use the Text to Speech, the MemoryStream returns json as the first Accept is "application/json".
If you try to use Synthesize and get the MemoryStream, the stream is actually a json file as the Accept header is application/json,application/xml,audio/mp3 and so at least in a console app, the first thing it can accept is json, so it will return json. by clearing out all the accept only when there's audio present, the audio gets first dibs.

fix(http request): Cleared out accept header if a file is returned

---

src/IBM.WatsonDeveloperCloud/Service/WatsonService.cs
src/IBM.WatsonDeveloperCloud/Util/Credentials.cs
src/IBM.WatsonDeveloperCloud/Util/Utility.cs
test/IBM.WatsonDeveloperCloud.Assistant.v1.UnitTests/AssistantUnitTests.cs
test/IBM.WatsonDeveloperCloud.SpeechToText.v1.IntegrationTests/SpeechToTextServiceIntegrationTest.cs

This pull request throws an error if the username, password, apikey or service url has `{` or `"` in the beginning of the string or `}` or `"` at the end of the string.

Check for bad characters in username, password, apiKey and service Url

---

.bumpversion.cfg
.releaserc
appveyor.yml

This pull request implements bumpversion to the build process. This will allow us to do a release without creating an rc branch to manually bump version. Additionally we should be able to delete the develop branch of the repo and do automatic releases as feature branches are merged into master. 
Note: We have to use an alternate version of bumpversion since there is a commit error in Windows with the current version. 
Also `semantic-release` is being called before the `dotnet pack` step so we pack the bumpversion change. This is fine since the deploy is happening at the end of the appveyor build rather than in `semantic-release`.

Implement bumpversion

---

.secrets.baseline
appveyor.yml

This pull request updates NuGet apikey and moves semantic-release to after tests. Additionally we add the python module directory to the paths.

ci: Updated NuGet apikey, moved semantic-release after tests

---

src/IBM.WatsonDeveloperCloud.Assistant.v1/AssistantService.cs
src/IBM.WatsonDeveloperCloud.Assistant.v2/AssistantService.cs
src/IBM.WatsonDeveloperCloud.CompareComply.v1/CompareComplyService.cs
src/IBM.WatsonDeveloperCloud.Discovery.v1/DiscoveryService.cs
src/IBM.WatsonDeveloperCloud.LanguageTranslator.v3/LanguageTranslatorService.cs
src/IBM.WatsonDeveloperCloud.NaturalLanguageClassifier.v1/NaturalLanguageClassifierService.cs
src/IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1/NaturalLanguageUnderstandingService.cs
src/IBM.WatsonDeveloperCloud.PersonalityInsights.v3/PersonalityInsightsService.cs
src/IBM.WatsonDeveloperCloud.SpeechToText.v1/SpeechToTextService.cs
src/IBM.WatsonDeveloperCloud.SpeechToText.v1/SpeechToTextServiceExtension.cs
src/IBM.WatsonDeveloperCloud.TextToSpeech.v1/TextToSpeechService.cs
src/IBM.WatsonDeveloperCloud.ToneAnalyzer.v3/ToneAnalyzerService.cs
src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/VisualRecognitionService.cs
src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/VisualRecognitionServiceExtension.cs
src/IBM.WatsonDeveloperCloud/Constants.cs
src/IBM.WatsonDeveloperCloud/Http/HttpFactory.cs

This pull request adds environment info to the user-agent header. I also added `X-IBMCloud-SDK-Analytics` header to each operation.
`User-Agent` `watson-apis-dotnet-sdk-2.13.0 MicrosoftWindows 10.0.17134 .NETCore4.6.25211.02`

chore(User-Agent): Updated user-agent to include environment information

---

src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/VisualRecognitionService.cs
test/IBM.WatsonDeveloperCloud.VisualRecognition.v3.IntegrationTests/VisualRecognitionServiceIntegrationTests.cs

Fixes https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/312
This pull request fixes the Visual Recognition Classify method. I was not considering the culture when converting float to string at the threshold.

fixed: VR classify threshold with invariant culture

---

IBM.Watson.sln
appveyor.yml
src/IBM.Watson.Common/Common.cs
src/IBM.Watson.Common/IBM.Watson.Common.csproj
test/IBM.Watson.IntegrationTests/CommonIntegrationTests.cs
test/IBM.Watson.IntegrationTests/CoreIntegrationTests.cs
test/IBM.Watson.IntegrationTests/IBM.Watson.IntegrationTests.csproj

This pull request adds a common class for the Watson .NET SDK. This contains mostly functionality to get headers for rest requests. This PR does not include implementing this in the service abstractions - Phil has already added this to the generator. Additionally issues https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/335 and https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/342 point out that certain characters are causing issues in getting analytics headers. We remove the characters in `CleanupString`. 
One thing to note is that the OS info isn't consistent across platforms. For example
Windows: 
`Microsoft Windows 10.0.17134 `
OSX
`Darwin 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64`
Linux …

feat(Common): Added a Common package for Watson specific functionality

---

src/IBM.WatsonDeveloperCloud/Http/HttpFactory.cs
src/IBM.WatsonDeveloperCloud/Util/Utility.cs
test/IBM.WatsonDeveloperCloud.Core.IntegrationTests/UserAgentParsingTests.cs

fixes https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/335
fixes https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/342
Getting OS and OS Version for user-agent header was causing errors in different operating systems.
This functionality was updated to clean up the strings and get a generalized OS for user-agent.
Output for user-agent on windows is
```
User-Agent, watson-apis-dotnet-standard-sdk-2.16.0 Windows 10.0.17134 .NET-Core-4.6.26328.01
```

fix(User-Agent): Updated method of getting OS and OS version

---

.releaserc
appveyor.yml
src/IBM.WatsonDeveloperCloud/Http/HttpFactory.cs
src/IBM.WatsonDeveloperCloud/Util/Utility.cs
test/IBM.WatsonDeveloperCloud.Core.IntegrationTests/UserAgentParsingTests.cs

https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/344 inadvertently released .NET SDK v3.0.0. This was due to a breaking change that was inadvertently [merged](https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/336) and [reverted](https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/338) but the `BREAKING CHANGE` annotation was still in the git history of the `master` branch. 
I created a `v2.x.x` branch from before #344 was merged, created a feature branch and cherry-picked `0f4678d` which was the only change to v2 of the SDK. I changed semantic release and Appveyor scripts to release and deploy on merge to the `v2.x.x` branch. This should correctly build and deploy .NET SDK `v2.16.1` to Nuget.
We will use the `v2.x.x` branch for any updates …

Parse user agent

---

.bumpversion.cfg

Currently ci is skipped on the tagged build. This results in documentation not being generated for the tagged build. This pull request removes `skip ci` from bumpversion.cfg so documentation is generated.

Removed `skip ci` from bumpversion.cfg

---

appveyor.yml

Discovery v2 was deployed manually to Nuget because of an error in the csproj path. This PR corrects the path so we don't run into this issue for next release.

Update deploy step to correct discovery v2 path

---

README.md

This pull request updates the readme to describe how to get the global transaction id of an api call.

Update readme to describe how to get the global transaction id

---

test/Assistant.v1.IntegrationTests/IBM.Watson.Assistant.v1.IntegrationTests.csproj
test/Assistant.v1.UnitTests/IBM.Watson.Assistant.v1.UnitTests.csproj
test/Assistant.v2.IntegrationTests/IBM.Watson.Assistant.v2.IntegrationTests.csproj
test/Assistant.v2.UnitTests/IBM.Watson.Assistant.v2.UnitTests.csproj
test/CompareComply.v1.IntegrationTests/IBM.Watson.CompareComply.v1.IntegrationTests.csproj
test/CompareComply.v1.UnitTests/IBM.Watson.CompareComply.v1.UnitTests.csproj
test/Discovery.v1.IntegrationTests/IBM.Watson.Discovery.v1.IntegrationTests.csproj
test/Discovery.v1.UnitTests/IBM.Watson.Discovery.v1.UnitTests.csproj
test/Discovery.v2.IntegrationTests/IBM.Watson.Discovery.v2.IntegrationTests.csproj
test/Discovery.v2.UnitTests/IBM.Watson.Discovery.v2.UnitTests.csproj
test/IBM.Watson.IntegrationTests/IBM.Watson.IntegrationTests.csproj
test/LanguageTranslator.v3.IntegrationTests/IBM.Watson.LanguageTranslator.v3.IntegrationTests.csproj
test/LanguageTranslator.v3.UnitTests/IBM.Watson.LanguageTranslator.v3.UnitTests.csproj
test/NaturalLanguageClassifier.v1.IntegrationTests/IBM.Watson.NaturalLanguageClassifier.v1.IntegrationTests.csproj
test/NaturalLanguageClassifier.v1.UnitTests/IBM.Watson.NaturalLanguageClassifier.v1.UnitTests.csproj
test/NaturalLanguageUnderstanding.v1.IntegrationTests/IBM.Watson.NaturalLanguageUnderstanding.v1.IntegrationTests.csproj
test/NaturalLanguageUnderstanding.v1.UnitTests/IBM.Watson.NaturalLanguageUnderstanding.v1.UnitTests.csproj
test/PersonalityInsights.v3.IntegrationTests/IBM.Watson.PersonalityInsights.v3.IntegrationTests.csproj
test/PersonalityInsights.v3.UnitTests/IBM.Watson.PersonalityInsights.v3.UnitTests.csproj
test/SpeechToText.v1.IntegrationTests/IBM.Watson.SpeechToText.v1.IntegrationTests.csproj
test/SpeechToText.v1.UnitTests/IBM.Watson.SpeechToText.v1.UnitTests.csproj
test/TextToSpeech.v1.IntegrationTests/IBM.Watson.TextToSpeech.v1.IntegrationTests.csproj
test/TextToSpeech.v1.UnitTests/IBM.Watson.TextToSpeech.v1.UnitTests.csproj
test/ToneAnalyzer.v3.IntegrationTests/IBM.Watson.ToneAnalyzer.v3.IntegrationTests.csproj
test/ToneAnalyzer.v3.UnitTests/IBM.Watson.ToneAnalyzer.v3.UnitTests.csproj
test/VisualRecognition.v3.IntegrationTests/IBM.Watson.VisualRecognition.v3.IntegrationTests.csproj
test/VisualRecognition.v3.UnitTests/IBM.Watson.VisualRecognition.v3.UnitTests.csproj
test/VisualRecognition.v4.IntegrationTests/IBM.Watson.VisualRecognition.v4.IntegrationTests.csproj
test/VisualRecognition.v4.UnitTests/IBM.Watson.VisualRecognition.v4.UnitTests.csproj

The dependency version for NSubstitute was inadvertently updated via bumpversion causing an error in ci build. This pull request restores the dependency to the correct version.

Restore dependency version

---

appveyor.yml

nodejs is now set to 12.13.0 to successfully build .NET tests

build(appveyor.yml): nodejs is now set to 12.13.0
