watson-developer-cloud/dotnet-standard-sdk

- src/IBM.WatsonDeveloperCloud.ToneAnalyzer/README.md
- src/IBM.WatsonDeveloperCloud.ToneAnalyzer/v3/ToneAnalyzerService.cs
- test/IBM.WatsonDeveloperCloud.ToneAnalyzer.IntegrationTests/ToneAnalyzerServiceIntegrationTest.cs
- test/IBM.WatsonDeveloperCloud.ToneAnalyzer.UnitTests/ToneAnalyzerServiceUnitTest.cs
Refactoring `ToneAnalizerService` to `ToneAnalyzerService` in the cs file and ReadMe.
> Refactor ToneAnalizerService to ToneAnalyzerService

- .github/CONTRIBUTING.md
First revision to code standard. Let's look this over.
> Updated contributing.md with coding standards.

- IBM.WatsonDeveloperCloud.sln
- examples/IBM.WatsonDeveloperCloud.Conversation.Example/ConversationServiceExample.cs
- examples/IBM.WatsonDeveloperCloud.Conversation.Example/Example.cs
- examples/IBM.WatsonDeveloperCloud.Conversation.Example/IBM.WatsonDeveloperCloud.Conversation.Example.xproj
- examples/IBM.WatsonDeveloperCloud.Conversation.Example/Properties/AssemblyInfo.cs
- examples/IBM.WatsonDeveloperCloud.Conversation.Example/project.json
- src/IBM.WatsonDeveloperCloud.Conversation/README.md
Created an example project testing the Message endpoint in Conversation and updated the ReadMe.md for the Conversation service. The service doesn't seem to work but I want to merge the examples in for testing.
> Gh 43 conversation sample

- src/IBM.WatsonDeveloperCloud.Conversation/IBM.WatsonDeveloperCloud.Conversation.nuspec
- src/IBM.WatsonDeveloperCloud.Discovery/IBM.WatsonDeveloperCloud.Discovery.nuspec
- src/IBM.WatsonDeveloperCloud.LanguageTranslator/IBM.WatsonDeveloperCloud.LanguageTranslator.nuspec
- src/IBM.WatsonDeveloperCloud.PersonalityInsights/IBM.WatsonDeveloperCloud.PersonalityInsights.nuspec
- src/IBM.WatsonDeveloperCloud.SpeechToText/IBM.WatsonDeveloperCloud.SpeechToText.nuspec
- src/IBM.WatsonDeveloperCloud.TextToSpeech/IBM.WatsonDeveloperCloud.TextToSpeech.nuspec
- src/IBM.WatsonDeveloperCloud.ToneAnalyzer/IBM.WatsonDeveloperCloud.ToneAnalyzer.nuspec
- src/IBM.WatsonDeveloperCloud.VisualRecognition/IBM.WatsonDeveloperCloud.VisualRecognition.nuspec
- src/IBM.WatsonDeveloperCloud/IBM.WatsonDeveloperCloud.nuspec
Generating nuspec files for nuget deployment.
> generate and populate nuspec files for deployment

- README.md
Update coveralls badge to track development branch rather than master
> update coveralls badge to track development branch

- appveyor.yml
- src/IBM.WatsonDeveloperCloud.LanguageTranslator/v2/ILanguageTranslatorService.cs
fix errors in automatic documentation generation
> Hotfix missing documentation

- src/IBM.WatsonDeveloperCloud.SpeechToText/v1/ISpeechToTextService.cs
- src/IBM.WatsonDeveloperCloud.VisualRecognition/v3/IVisualRecognitionService.cs
Update documentation for errors and warnings
> Hotfix update documentation

- README.md
Added service version to service links in readme.
> fixes #108 add version to service links

- appveyor.yml
- src/IBM.WatsonDeveloperCloud.Conversation.v1/project.json
- src/IBM.WatsonDeveloperCloud.Discovery.v1/project.json
- src/IBM.WatsonDeveloperCloud.LanguageTranslator.v2/project.json
- src/IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1/project.json
- src/IBM.WatsonDeveloperCloud.PersonalityInsights.v3/project.json
- src/IBM.WatsonDeveloperCloud.SpeechToText.v1/project.json
- src/IBM.WatsonDeveloperCloud.TextToSpeech.v1/project.json
- src/IBM.WatsonDeveloperCloud.ToneAnalyzer.v3/project.json
- src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/project.json
- src/IBM.WatsonDeveloperCloud/project.json
Update each project.json file to include metadata for packaging for nuget. Also versioning up appveyor yml to build for next release version.
> Updating projectjson

- appveyor.yml
Updating appveyor build version to 1.2 before starting work 1.2.0
> update appveyor yml to build 1.2.{build}

- appveyor.yml
> update version in appveyor before starting v1.3.0

- src/IBM.WatsonDeveloperCloud/Http/Extensions/UriExtensions.cs
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here.
Thanks for contributing to the Watson Developer Cloud!
> fix: camelcase values in querystring

- test/IBM.WatsonDeveloperCloud.Discovery.v1.IntegrationTests/DiscoveryIntegrationTests.cs
Tests are failing because of this operation. Disabling the test until I can take a closer look at it. Also removing some generated test files.
> disable failing PreviewEnvironment test in Discovery

- examples/IBM.WatsonDeveloperCloud.VisualRecognition.v3.Example/VisualRecognitionServiceExample.cs
- src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/VisualRecognitionService.cs
- test/IBM.WatsonDeveloperCloud.VisualRecognition.v3.IntegrationTests/VisualRecognitionServiceIntegrationTests.cs
Form parameters in classify were missing names. Added names, updated examples and tests
> Update Classify Parameters

- Doxyfile
- appveyor.yml
- test/IBM.WatsonDeveloperCloud.SpeechToText.v1.IntegrationTests/SpeechToTextServiceIntegrationTest.cs
Update project number in documentation, look into failing integration tests, update expired nuget apikey.
> Hotfix 1.3.0 integration tests

- src/IBM.WatsonDeveloperCloud.Conversation.v1/Model/MessageRequest.cs
Make `Context` dynamic in `MessageRequest`.
> make context  dynamic in MessageRequest

- CHANGELOG.md
- Doxyfile
- src/IBM.WatsonDeveloperCloud.Conversation.v1/README.md
- src/IBM.WatsonDeveloperCloud.Discovery.v1/README.md
- src/IBM.WatsonDeveloperCloud.LanguageTranslator.v2/README.md
- src/IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1/README.md
- src/IBM.WatsonDeveloperCloud.PersonalityInsights.v3/README.md
- src/IBM.WatsonDeveloperCloud.SpeechToText.v1/README.md
- src/IBM.WatsonDeveloperCloud.TextToSpeech.v1/README.md
- src/IBM.WatsonDeveloperCloud.ToneAnalyzer.v3/README.md
- src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/README.md
- src/IBM.WatsonDeveloperCloud/README.md
Merge release changes back into `development`.
> Merge rc-1.3.1 into development

- src/IBM.WatsonDeveloperCloud.TextToSpeech.v1/TextToSpeechService.cs
- test/IBM.WatsonDeveloperCloud.TextToSpeech.v1.IntegrationTests/TextToSpeechServiceIntegrationTests.cs
Accept header was causing issues with synthesize - moved it to query param for now.
> move accept from header to query param

- src/IBM.WatsonDeveloperCloud.NaturalLanguageClassifier.v1/IBM.WatsonDeveloperCloud.NaturalLanguageClassifier.v1.csproj
- src/IBM.WatsonDeveloperCloud.NaturalLanguageClassifier.v1/Model/ClassificationCollection.cs
- src/IBM.WatsonDeveloperCloud.NaturalLanguageClassifier.v1/Model/ClassifyCollectionInput.cs
- src/IBM.WatsonDeveloperCloud.NaturalLanguageClassifier.v1/Model/CollectionItem.cs
- src/IBM.WatsonDeveloperCloud.NaturalLanguageClassifier.v1/NaturalLanguageClassifierService.cs
- test/IBM.WatsonDeveloperCloud.NLC.v1.IntegrationTests/NaturalLanguageClassifierServiceIntegrationTests.cs
regenerate NLC and write test for ClassifyCollection
> Natural Language Classifier: Classify Collection

- IBM.WatsonDeveloperCloud.sln
- examples/IBM.WatsonDeveloperCloud.TextToSpeech.v1.Example/IBM.WatsonDeveloperCloud.TextToSpeech.v1.Example.csproj
- examples/IBM.WatsonDeveloperCloud.TextToSpeech.v1.Example/Program.cs
Added missing example for TextToSpeech, following the same pattern from SpeechToText.
Done tests with the Example and worked fine.
Thanks for contributing to the Watson Developer Cloud!
> Added Example for TextToSpeech

- src/IBM.WatsonDeveloperCloud.Discovery.v1/README.md
This pull request revises the example for the AddDocument method in Discovery.
> update AddDocument example

- README.md
- src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/README.md
- src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/VisualRecognitionService.cs
- src/IBM.WatsonDeveloperCloud/Service/WatsonService.cs
This pull request revises the ReadMe file showing how to instantiate the Visual Recognition service. It also moves tokenManager to the service base class and adds a SetCredential(TokenOptions) method in the base class.
> Revise readme for Visual Recognition CF authentication

- README.md
- src/IBM.WatsonDeveloperCloud/Service/IWatsonService.cs
- src/IBM.WatsonDeveloperCloud/Service/WatsonService.cs
- test/IBM.WatsonDeveloperCloud.Assistant.v1.IntegrationTests/AssistantServiceIntegrationTests.cs
- test/IBM.WatsonDeveloperCloud.Discovery.v1.IntegrationTests/DiscoveryIntegrationTests.cs
- test/IBM.WatsonDeveloperCloud.LanguageTranslator.v2.IntegrationTests/LanguageTranslatorServiceIntegrationTests.cs
- test/IBM.WatsonDeveloperCloud.NLC.v1.IntegrationTests/NaturalLanguageClassifierServiceIntegrationTests.cs
- test/IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1.IntTests/NaturalLanguageUnderstandingIntegrationTests.cs
- test/IBM.WatsonDeveloperCloud.SpeechToText.v1.IntegrationTests/SpeechToTextServiceIntegrationTest.cs
- test/IBM.WatsonDeveloperCloud.TextToSpeech.v1.IntegrationTests/TextToSpeechServiceIntegrationTests.cs
This pull request adds a method for the user to set the service endpoint. Additionally, I added a method to SetCredentials using TokenOptions. The SDK will check if the user manually changed the service endpoint and if so will not automatically change the endpoint. 
Finally, I hardcoded the VisualRecognition endpoint when SetCredential(apikey) is invoked.
> User set endpoint

- src/IBM.WatsonDeveloperCloud.Assistant.v1/AssistantService.cs
- src/IBM.WatsonDeveloperCloud.Assistant.v1/Model/CreateValue.cs
- src/IBM.WatsonDeveloperCloud.Assistant.v1/Model/UpdateValue.cs
- src/IBM.WatsonDeveloperCloud.Conversation.v1/ConversationService.cs
- src/IBM.WatsonDeveloperCloud.Conversation.v1/Model/CreateValue.cs
- src/IBM.WatsonDeveloperCloud.Conversation.v1/Model/UpdateValue.cs
- src/IBM.WatsonDeveloperCloud.Discovery.v1/DiscoveryService.cs
- src/IBM.WatsonDeveloperCloud.LanguageTranslator.v2/LanguageTranslatorService.cs
- src/IBM.WatsonDeveloperCloud.NaturalLanguageClassifier.v1/NaturalLanguageClassifierService.cs
- src/IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1/NaturalLanguageUnderstandingService.cs
- src/IBM.WatsonDeveloperCloud.PersonalityInsights.v3/IPersonalityInsightsService.cs
- src/IBM.WatsonDeveloperCloud.PersonalityInsights.v3/PersonalityInsightsService.cs
- src/IBM.WatsonDeveloperCloud.SpeechToText.v1/ISpeechToTextService.cs
- src/IBM.WatsonDeveloperCloud.SpeechToText.v1/Model/AudioResources.cs
- src/IBM.WatsonDeveloperCloud.SpeechToText.v1/SpeechToTextService.cs
- src/IBM.WatsonDeveloperCloud.TextToSpeech.v1/TextToSpeechService.cs
- src/IBM.WatsonDeveloperCloud.ToneAnalyzer.v3/IToneAnalyzerService.cs
- src/IBM.WatsonDeveloperCloud.ToneAnalyzer.v3/ToneAnalyzerService.cs
- src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/VisualRecognitionService.cs
This pull request regenerates the SDK with IAM support for Natural Language Classifier.
> Regenerate SDK with IAM support for NLC

- README.md
- src/IBM.WatsonDeveloperCloud.Assistant.v1/README.md
- src/IBM.WatsonDeveloperCloud.Conversation.v1/README.md
- src/IBM.WatsonDeveloperCloud.Discovery.v1/README.md
- src/IBM.WatsonDeveloperCloud.LanguageTranslator.v2/README.md
- src/IBM.WatsonDeveloperCloud.LanguageTranslator.v3/README.md
- src/IBM.WatsonDeveloperCloud.NaturalLanguageClassifier.v1/README.md
- src/IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1/README.md
- src/IBM.WatsonDeveloperCloud.PersonalityInsights.v3/README.md
- src/IBM.WatsonDeveloperCloud.SpeechToText.v1/README.md
- src/IBM.WatsonDeveloperCloud.ToneAnalyzer.v3/README.md
- src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/README.md
This pull request updates the main README file with authentication instructions pulled from https://github.com/watson-developer-cloud/java-sdk/pull/954
Additionally, authentication instructions from service readme pages were removed.
> Update readme with Allen's suggestions

- README.md
This pull request adds a `Before You Begin` section and a dotnet sdk specific tracking link for IBM Cloud onboarding.
> update readme with tracking link

- README.md
- src/IBM.WatsonDeveloperCloud.LanguageTranslator.v2/LanguageTranslatorService.cs
- src/IBM.WatsonDeveloperCloud.LanguageTranslator.v2/README.md
This pull request adds a deprecation notice to the Language Translator V2 constructor. Additionally , readme files were updated to include the deprecation notice.
> Language Translator v2 deprecation notice

- src/IBM.WatsonDeveloperCloud.Assistant.v2/IBM.WatsonDeveloperCloud.Assistant.v2.csproj
- test/IBM.WatsonDeveloperCloud.Discovery.v1.IntegrationTests/DiscoveryIntegrationTests.cs
This release merges in release changes to the develop branch
> Merge in release changes

- src/IBM.WatsonDeveloperCloud/Http/WatsonHttpClient.cs
This pull request addresses an issue with disabling SSL verification when making a REST call. I have validated Assistant and Speech to Text on ICP.
> Disable SSL

- src/IBM.WatsonDeveloperCloud.SpeechToText.v1/SpeechToTextServiceExtension.cs
This pull request fixes the Speech to Text Recognize method. We were not sending specified model in the recognize call.
> Fixed sending language model in Recognize

- README.md
- src/IBM.WatsonDeveloperCloud.Assistant.v2/README.md
This pull request removes beta from Assistant V2 readme documentation.
> Remove beta from Assistant V2 documentation

- .pre-commit-config.yaml
- .secrets.baseline
This pull request adds config files for `detect-secrets` via pre-commit hook.
> Detect secrets

- .secrets.baseline
- appveyor.yml
> ci(Updated python path):

- README.md
This pull request adds a request for featured projects using the SDK to the readme.
> Add request for featured projects to the readme

- README.md
This pull request adds a request for projects to be featured on the .NET SDK readme.
> Add featured projects section to readme

- .bumpversion.cfg
- .secrets.baseline
- appveyor.yml
> build: Add correct paths to bumpversion, attempting to fix download credentials

- .github/ISSUE_TEMPLATE/bug_report.md
- .utility/generate_html.ps1
- README.md
This pull request refactors `bluemix` to `cloud.ibm`
> Refactored bluemix to cloud.ibm

- README.md
Found a few more references to bluemix.
> Refactor bluemix to cloud.ibm

- IBM.Watson.sln
- examples/IBM.Watson.PersonalityInsights.v3.Examples/IBM.Watson.PersonalityInsights.v3.Examples.csproj
- examples/IBM.Watson.PersonalityInsights.v3.Examples/ServiceExample.cs
This pull request adds Natural Language Understanding V1 examples to the SDK
> Add Personality Insights V3 examples

- IBM.Watson.sln
- examples/IBM.Watson.ToneAnalyzer.v3.Examples/IBM.Watson.ToneAnalyzer.v3.Examples.csproj
- examples/IBM.Watson.ToneAnalyzer.v3.Examples/ServiceExample.cs
Summary This pull request adds Text to Speech V1 examples to the SDK
> Add Tone Analyzer V3 examples

- README.md
Fixes #386 
This pull request updates the links for the services since we removed outdated service readme files.
> Updated service links

- README.md
This pull request updates case for parameters when instantiating an authConfig in the readme.
> Corrected param case when instantiating config

- docker/Dockerfile
- docker/README.md
Added dockerfile to .net sdk to create an image with the sdk installed that can be used for testing issues.
> .NET SDK Dockerfile

- src/IBM.Watson.CompareComply.v1/Model/KeyValuePair.cs
- test/CompareComply.v1.UnitTests/CompareComplyTestData/table-return.json
- test/CompareComply.v1.UnitTests/CompareComplyV1UnitTests.cs
- test/CompareComply.v1.UnitTests/IBM.Watson.CompareComply.v1.UnitTests.csproj
This pull request corrects the type of `Value` in the `KeyValuePair`
> Fix Value type in KeyValuePair model

- examples/IBM.Watson.NaturalLanguageUnderstanding.v1.Examples/ServiceExample.cs
- test/NaturalLanguageUnderstanding.v1.IntegrationTests/NaturalLanguageUnderstandingIntegrationTests.cs
This pull request adds NLU tests and examples to the .NET SDK
> NLU tests and examples

- .bumpversion.cfg
This pull request updates bumpversion with the latest projects
> Update bumpversion with new projects

- appveyor.yml
This pull request removes the npm update added to fix broken release.
> build(npm): Remove updating npm

- .releaserc
- package-lock.json
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here.
Thanks for contributing to the Watson Developer Cloud!
> build: Update releaserc

- src/IBM.Watson.NaturalLanguageUnderstanding.v1/Model/CategoriesOptions.cs
This pull request restores a field in CategoriesOptions that was removed in the last release cycle.
> Restore categories model

- src/IBM.Watson.Common/Common.cs
- src/IBM.Watson.Common/IBM.Watson.Common.csproj
This pull request versions up common library. The nuget package was deployed but the change was never committed to the codebase.
> chore: Version common libraries

- appveyor.yml
This pull request tests semantic release. Previously the build was failing due to powershell throwing an error when a tool (git and npx in this case) writes to StdErr. The deployment goes as planned but the build shows up as broken. Testing to see if this helps.
> Test semantic release

- .releaserc
- appveyor.yml
This pull request attempts to match Unity SDK semantic release script.
> build(Semantic Release): Match Unity

- examples/IBM.Watson.Assistant.v2.Examples/ServiceExample.cs
This is the most recommended for C #
For more information: [link](https://docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/classes-and-structs/using-properties)
> Adjustment in MessageContext of Assistant_V2

- src/IBM.Watson.Assistant.v1/Model/DialogNodeOutputGeneric.cs
This pull request updates outdated docs links in generated code.
> Update outdated docs link

- src/IBM.Watson.Common/Common.cs
- src/IBM.Watson.Common/IBM.Watson.Common.csproj
updated version in common library to 4.6.0
> chore(common): update common version

- README.md
This pull request adds information on setting global transaction id in a request.
> Add documentation on setting transaction id

- .bumpversion.cfg
build errored out because bumpversion.cfg didn't have the correct paths
> build(bumpversion): update bumpversion cfg for file paths

- appveyor.yml
Previous key was failing on appveyor, updating with my encrypted api key
> ci(appveyor): update api_key for nuget

- src/IBM.Watson.TextToSpeech.v1/Websockets/AWebSocketClient.cs
Error is now parsed from the service response
> fix(text-to-speech): parse error message from websocket

- .github/workflows/deploy.yml
> ci: fix commit to gh_pages

- .github/workflows/deploy.yml
Continue when docs already exist
> ci: do not fail on duplicate push

- src/IBM.Watson.NaturalLanguageClassifier.v1/NaturalLanguageClassifierService.cs
add deprecation warning to NLC constructor
fix #9626
> fix(nlc): add deprecation warning

- src/IBM.Watson.Common/Common.cs
- src/IBM.Watson.Common/IBM.Watson.Common.csproj
> chore: update common package

- README.md
This pull request adds deprecated tag to NLC in the readme
> docs: add deprecated tag to NLC

- .github/workflows/deploy.yml
- .github/workflows/integration-test.yml
- src/IBM.Watson.Discovery.v2/Test/Integration/DiscoveryIntegrationTests.cs
- src/IBM.Watson.LanguageTranslator.v3/Test/Integration/LanguageTranslatorServiceIntegrationTests.cs
Add the integration test workflow
> ci: Gha 9919
